title: Nereon
description: >-
  Universal configuration model, schema and syntax
  for processes, containers and more.
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

tagline: >-
  Consolidated configuration<br>for every process and container

pitch: >-
  Because the configuration expectations of your software
  deserve to be managed consistently.

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc/nereon

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/specs/nereon-syntax/", title: "Read the Specs" }
  - { url: "/software/", title: "See the Ecosystem" }

permalink: /blog/:month-:day-:year/:title/

url: https://nereon.com/
